---
- name: Installeren van Docker Engine & Compose
  apt:
    name: [docker.io, docker-compose]
    state: present
    update_cache: yes

- name: Docker service inschakelen
  service:
    name: docker
    state: started
    enabled: yes

- name: Container mappen aanmaken (zoals in .gitignore)
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/pld/caddy
    - /opt/pld/homeassistant
    - /opt/pld/vaultwarden
    - /opt/pld/mosquitto

- name: Installeer Apt-Cacher-NG voor snelle LAN-installaties
  apt:
    name: apt-cacher-ng
    state: present
    update_cache: yes

- name: Zorg dat Apt-Cacher-NG luistert op alle netwerkinterfaces
  lineinfile:
    path: /etc/apt-cacher-ng/acng.conf
    regexp: '^#?BindAddress:'
    line: 'BindAddress: 0.0.0.0'
  notify: Herstart Apt-Cacher
