---
- name: Richt de PLD Server in
  hosts: all
  become: yes
  roles:
    - network       # Hardware check + IP 192.168.100.1 + NAT Routing
    - dhcp          # Deelt IP-adressen uit aan de desktops
    - webserver     # Serveert bootstrap.sh via http://192.168.100.1
    - apt_proxy     # Cache voor razendsnelle installaties
